---
image: ubuntu
stages:
  - testing
  - production

test_laravel_server:
  stage: testing
  only:
    - master
  variables:
    DEBIAN_FRONTEND: noninteractive
    APP_ENV: development
    DB_CONNECTION: sqlite
    COMPOSER_ALLOW_SUPERUSER: 1
  before_script:
    - apt update
    - apt install php7.2-common php7.2-cli php7.2-gd php7.2-mysql php7.2-sqlite3 php7.2-curl php7.2-intl php7.2-mbstring php7.2-bcmath php7.2-imap php7.2-xml php7.2-zip curl -y
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - cd Backend/
    - composer install
    - php artisan storage:link
    - rm .env.example
    - touch .env && echo "APP_KEY=" >> .env
    - touch database/database.sqlite
    - php artisan key:generate
    - php artisan migrate
  script:
    - php artisan serve --host 0.0.0.0 &

deploy:
  stage: production
  only:
    - master
  before_script: 
    - apt update
    - apt install openssh-client -y
    - mkdir -p ~/.ssh
    - echo -e "$DATABAE_PRIV_KEY" > ~/.ssh/id_rsa   
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh ubuntu@databaerecipes.com 'cd /var/www/laravel/DataBae; git pull'
    - echo "success!!"